# Generated by Django 6.0.2 on 2026-02-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
