# Generated by Django 6.0.2 on 2026-02-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanes', '0002_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
