# Generated by Django 6.0.2 on 2026-02-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanes', '0003_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaneTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
