# Generated by Django 6.0.2 on 2026-02-25 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanes', '0004_lanetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=7, null=True)),
                ('end_date', models.CharField(blank=True, max_length=7, null=True)),
                ('present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='LaneTitle',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='entry',
            name='lane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanes.lane'),
        ),
    ]
