# Generated by Django 6.0.2 on 2026-02-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanes', '0005_entry_lane_delete_lanetitle_delete_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lane', models.IntegerField()),
                ('start_date', models.CharField(blank=True, max_length=7, null=True)),
                ('end_date', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Lane',
        ),
    ]
