# Generated by Django 6.0.2 on 2026-02-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanes', '0006_project_delete_entry_delete_lane'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Entry',
        ),
    ]
