# Generated by Django 6.0.2 on 2026-02-25 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanes', '0007_rename_project_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='lane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='lanes.lane'),
        ),
    ]
