# Generated by Django 6.0.2 on 2026-02-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanes', '0009_entry_user_lane_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='start_date',
        ),
        migrations.AddField(
            model_name='entry',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
